// Copyright 2017 Baliance. All rights reserved.
//
// DO NOT EDIT: generated by gooxml ECMA-376 generator
//
// Use of this source code is governed by the terms of the Affero GNU General
// Public License version 3.0 as published by the Free Software Foundation and
// appearing in the file LICENSE included in the packaging of this file. A
// commercial license can be purchased by contacting sales@baliance.com.

package wml

import (
	"encoding/xml"
	"fmt"
)

type CT_ShapeWrap struct {
	TypeAttr *string
}

func NewCT_ShapeWrap() *CT_ShapeWrap {
	return &CT_ShapeWrap{}
}

func (m *CT_ShapeWrap) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	// 属性编码 -  文本
	if m.TypeAttr != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "type"},
			Value: fmt.Sprintf("%v", *m.TypeAttr)})
	}

	e.EncodeToken(start)

	// 编码元素结构
	e.EncodeToken(xml.EndElement{Name: start.Name})
	return nil
}

func (m *CT_ShapeWrap) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {

	// initialize to default
	for _, attr := range start.Attr {
		if attr.Name.Local == "type" {
			parsed, err := attr.Value, error(nil)
			if err != nil {
				return err
			}
			m.TypeAttr = &parsed
			break
		}
	}
	for {
		tok, err := d.Token()
		if err != nil {
			return fmt.Errorf("parsing CT_ShapeWrap: %s", err)
		}
		if el, ok := tok.(xml.EndElement); ok && el.Name == start.Name {
			break
		}
	}
	return nil
}

// Validate validates the CT_ShapeWrap and its children
func (m *CT_ShapeWrap) Validate() error {
	return m.ValidateWithPath("CT_ShapeWrap")
}

// ValidateWithPath validates the CT_ShapeWrap and its children, prefixing error messages with path
func (m *CT_ShapeWrap) ValidateWithPath(path string) error {

	return nil
}
